# Generated by Django 4.1.7 on 2023-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(max_length=5)),
                ('sepal_width', models.FloatField(max_length=5)),
                ('petal_length', models.FloatField(max_length=5)),
                ('petal_width', models.FloatField(max_length=5)),
            ],
        ),
    ]
